'use strict';

module.exports = {
    MEDIA_TYPE: 'media_type',
    STREAM_INDEX: 'stream_index',
    KEY_FRAME: 'key_frame',
    BEST_EFFORT_TIMESTAMP: 'best_effort_timestamp',
    BEST_EFFORT_TIMESTAMP_TIME: 'best_effort_timestamp_time',
    PKT_POS: 'pkt_pos',
    PKT_SIZE: 'pkt_size',
    PKT_PTS: 'pkt_pts',
    PKT_PTS_TIME: 'pkt_pts_time',
    PKT_DTS: 'pkt_dts',
    PKT_DTS_TIME: 'pkt_dts_time',
    PKT_DURATION: 'pkt_duration',
    PKT_DURATION_TIME: 'pkt_duration_time',
    SAMPLE_FMT: 'sample_fmt',
    NB_SAMPLES: 'nb_samples',
    CHANNELS: 'channels',
    CHANNEL_LAYOUT: 'channel_layout',
    WIDTH: 'width',
    HEIGHT: 'height',
    PIX_FMT: 'pix_fmt',
    SAMPLE_ASPECT_RATIO: 'sample_aspect_ratio',
    PICT_TYPE: 'pict_type',
    CODED_PICTURE_NUMBER: 'coded_picture_number',
    DISPLAY_PICTURE_NUMBER: 'display_picture_number',
    INTERLACED_FRAME: 'interlaced_frame',
    TOP_FIELD_FIRST: 'top_field_first',
    REPEAT_PICT: 'repeat_pict',
    PTS: 'pts',
    PTS_TIME: 'pts_time',
    DURATION: 'duration',
    DURATION_TIME: 'duration_time',
};
